export const data = [{
  firstname: "Tony",
  lastname: "Stark",
  email: "ironman@sample.com",
  phone: "9999999999"
}, {
    firstname: "Peter",
    lastname: "Parker",
  email: "spiderman@sample.com",
  phone: "9054651553"
}, {
    firstname: "Thor",
    lastname: "Asgadien",
  email: "thor@Sample.com",
  phone: "9251514154"
}, {
    firstname: "Steven",
    lastname: "Rogers",
  email: "captainamerica@sample.com",
  phone: "9415481545"
}, {
    firstname: "Bruce",
    lastname: "Banner",
  email: "hulk@sample.com",
  phone: "9515451515"
}, {
    firstname: "Stephen",
    lastname: "Strange",
  email: "doctorstrange@sample.com",
  phone: "9898989898"
}, {
    firstname: "Henry",
    lastname: "Pym",
  email: "missstark@sample.com",
  phone: "9791581581"
}, {
    firstname: "Nicholas",
    lastname: "Fury",
  email: "shielddir@sample.com",
  phone: "9797979797"
}, {
    firstname: "Natalia",
    lastname: "Romanova",
  email: "widow@sample.com",
  phone: "900009999"
}, {
    firstname: "vision",
    lastname: "vision",
    email: "Vision@sample.com",
  phone: "900010000"
}, {
    firstname: "Tony",
    lastname: "Stark",
  email: "johndoe_eleven@sample.com",
  phone: "900011000"
}, {
    firstname: "Tony",
    lastname: "Stark",
  email: "ironman@sample.com",
  phone: "900012000"
}, {
    firstname: "Tony",
    lastname: "Stark",
    email: "ironman@sample.com",
  phone: "900013000"
}, {
    firstname: "Tony",
    lastname: "Stark",
    email: "ironman@sample.com",
  phone: "900014000"
}, {
    firstname: "Tony",
    lastname: "Stark",
    email: "ironman@sample.com",
  phone: "900015000"
}, {
    firstname: "Tony",
    lastname: "Stark",
    email: "ironman@sample.com",
  phone: "900016000"
}, {
    firstname: "Tony",
    lastname: "Stark",
    email: "ironman@sample.com",
  phone: "900017000"
}, {
    firstname: "Tony",
    lastname: "Stark",
    email: "ironman@sample.com",
  phone: "900018000"
}, {
    firstname: "Tony",
    lastname: "Stark",
    email: "ironman@sample.com",
  phone: "900019000"
}, {
    firstname: "Tony",
    lastname: "Stark",
    email: "ironman@sample.com",
  phone: "900020000"
}]